version: "3.8"

services:

  # Microserviço de Usuário
  usermicroservice:
    build: user
    ports:
      - "8081:8081"
    depends_on:
      - dbuser
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbuser:5432/usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - usernet       
      - rabbitnet     
      - gatewaynet    

  dbuser:
    image: postgres:15
    container_name: dbuser
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - usernet       
    volumes:
      - userdbdata:/var/lib/postgresql/data

  # Microserviço de Sala
  salamicroservice:
    build: sala
    ports:
      - "8082:8082"
    depends_on:
      - dbsala
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbsala:5432/salasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - salanet       
      - rabbitnet     
      - gatewaynet    

  dbsala:
    image: postgres:15
    container_name: dbsala
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: salasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - salanet       
    volumes:
      - saladbdata:/var/lib/postgresql/data

  # Microserviço de Reserva
  reservamicroservice:
    build: reserva
    ports:
      - "8083:8083"
    depends_on:
      - dbreserva
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbreserva:5432/reservasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - reservanet    
      - rabbitnet     
      - gatewaynet    

  dbreserva:
    image: postgres:15
    container_name: dbreserva
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - reservanet    
    volumes:
      - reservadbdata:/var/lib/postgresql/data

  # Gateway
  gateway:
    build: gateway
    ports:
      - "8080:8080"
    depends_on:
      - usermicroservice
      - salamicroservice
      - reservamicroservice
    networks:
      - gatewaynet    
      - usernet       
      - salanet       
      - reservanet    

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitnet     
      - usernet       
      - salanet       
      - reservanet   

  # Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    networks:
      - gatewaynet 

networks:
  gatewaynet:   
  rabbitnet:    
  usernet:      
  salanet:      
  reservanet:   

volumes:
  userdbdata:
  saladbdata:
  reservadbdata: